# Generated by Django 5.1.4 on 2025-05-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_item_company_name_purchaseorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='qty',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
