# Generated by Django 4.2.23 on 2025-08-14 11:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_remove_purchaseorderitem_purchase_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumedPurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('pack', models.CharField(max_length=100, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('hsn', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('consumed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_lines', to='myapp.consumedpurchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, null=True)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, null=True)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, null=True)),
                ('amount_in_words', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='myapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True,null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('pack', models.CharField(max_length=100, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('hsn', models.CharField(blank=True, max_length=200, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company_line',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='company_line',
            name='hsn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_line',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hsn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor'),
        ),
        migrations.AlterField(
            model_name='company_line',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_ids', to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='company_line',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=340.34, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_line',
            name='pack_size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_line',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company_line',
            name='stock_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('340.34'), max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pack_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='myapp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderapproval',
            name='purchase_order_line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaseorderapproval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='myapp.vendor'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='purchase_order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor'),
        ),
        migrations.AddField(
            model_name='consumedpurchaseorderline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
        migrations.AddField(
            model_name='consumedpurchaseorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
        migrations.AddField(
            model_name='consumedpurchaseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumedpurchaseorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumed_purchase_orders', to='myapp.vendor'),
        ),
    ]
