# Generated by Django 5.1.6 on 2026-04-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_date_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dateField',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='edit_allowed',
            field=models.CharField(blank=True, default='False', max_length=200, null=True),
        ),
    ]
