# Generated by Django 5.1.6 on 2026-04-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_invoice_datefield_registration_edit_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='amount',
        ),
        migrations.AddField(
            model_name='consumedpurchaseorder',
            name='dateField',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='dateField',
            field=models.DateField(blank=True, null=True),
        ),

    ]
