# Generated by Django 4.2.23 on 2026-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_invoice_date_remove_invoicelineitem_amount_and_more'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='registration',
            name='smtp_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
