# Generated by Django 6.0.5 on 2026-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_billingactivity_purchaseorderline_created_at_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
