# Generated by Django 6.0.5 on 2026-06-02 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_purchaseorderline_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),

        migrations.AddField(
            model_name='registration',
            name='payment_expiry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyinvoice',
            unique_together={('user', 'month', 'year')},
        ),
    ]
